name: acme_client
description: ACME client written in Dart
version: 1.2.0
homepage: https://github.com/Ephenodrom/Dart-Acme-Client
publish_to: https://pub.dartlang.org

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  basic_utils: ^5.5.0
  json_annotation: ^4.1.0
  dio:
    git:
      url: https://github.com/NOU-VANNET/dio.git
      ref: main
  jose: ^0.3.2

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.0
  build_runner: ^2.3.0
  json_serializable: ^6.6.1
